import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';
import Link from 'next/link';
import SocialSignin from '../../components/SocialSignin';
import { useState } from 'react';

export default function Register() {
  const router = useRouter();
  const [name, setName] = useState('');

  const login = () => {
    var form = document.getElementById('myForm');
    form.onsubmit = function (event) {
      var xhr = new XMLHttpRequest();
      var formData = new FormData(form);
      //open the request
      xhr.open('POST', 'https://cmid-be.herokuapp.com/auth/register', true);
      xhr.setRequestHeader('Content-Type', 'application/json');
      //send the form data
      xhr.send(JSON.stringify(Object.fromEntries(formData)));
      xhr.onreadystatechange = function () {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          // form.reset(); //reset form after AJAX success or do something else
          console.log(xhr.status, xhr.statusText);
          if (xhr.status === 201) {
            router.push({ pathname: '/confirm', query: { name: name } });
          } else {
            alert('Signup failed');
          }
        }
      };
      //Fail the onsubmit to avoid page refresh.
      return false;
    };
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CMID</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cooler Master CMID</h1>
        <div className={styles.appwrap}>
          <h1>Register</h1>
          <form id="myForm">
            <div>
              <input
                type="text"
                placeholder="Enter username"
                value={name}
                onChange={(e) => setName(e.target.value)}
                name="name"
                className={styles.input}
              />
            </div>
            <div>
              <input
                type="text"
                placeholder="Enter email"
                name="email"
                className={styles.input}
              />
            </div>
            <div>
              <input
                type="password"
                placeholder="Enter password"
                name="password"
                className={styles.input}
              />
            </div>
            <button className={styles.loginBtn} onClick={() => login()}>
              Sign up
            </button>
            <SocialSignin />
          </form>
          <div className={styles.registerOrSignin}>
            Already have an account?
            <Link href="/login" className={styles.registerOrSignin2}>
              {' '}
              Sign in
            </Link>
          </div>
        </div>
      </main>
    </div>
  );
}
