import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css';
import { useRouter } from 'next/router';
import Link from 'next/link';

export default function Confirm() {
  const router = useRouter();
  const name = router.query.name;
  console.log(name);
  const confirm = () => {
    var form = document.getElementById('myForm');
    form.onsubmit = function (event) {
      var xhr = new XMLHttpRequest();
      var formData = new FormData(form);
      //open the request
      xhr.open('POST', 'http://localhost:4000/auth/confirmSignup', true);
      xhr.setRequestHeader('Content-Type', 'application/json');
      //send the form data
      xhr.send(JSON.stringify(Object.fromEntries(formData)));
      xhr.onreadystatechange = function () {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          // form.reset(); //reset form after AJAX success or do something else
          console.log(xhr.status, xhr.statusText);
          if (xhr.status === 201) {
            router.push('/success');
          } else {
            alert('confirm failed, wrong code!');
          }
        }
      };
      //Fail the onsubmit to avoid page refresh.
      return false;
    };
  };

  const resend = () => {
    var form = document.getElementById('myForm2');
    form.onsubmit = function (event) {
      var xhr = new XMLHttpRequest();
      var formData = new FormData(form);
      //open the request
      xhr.open(
        'POST',
        'https://nest-aws-cognito.herokuapp.com/auth/resendCode',
        true,
      );
      xhr.setRequestHeader('Content-Type', 'application/json');
      //send the form data
      xhr.send(JSON.stringify(Object.fromEntries(formData)));
      xhr.onreadystatechange = function () {
        if (xhr.readyState === XMLHttpRequest.DONE) {
          // form.reset(); //reset form after AJAX success or do something else
          console.log(xhr.status, xhr.statusText);
          if (xhr.status === 201) {
            router.push('/confirm');
          } else {
            alert('confirm failed, wrong code!');
          }
        }
      };
      //Fail the onsubmit to avoid page refresh.
      return false;
    };
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>CMID</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Cooler Master CMID</h1>
        <div className={styles.appwrap}>
          <h1>Confirm your account</h1>
          <form id="myForm">
            <div>
              <input
                type="text"
                placeholder="Enter verification code"
                name="confirmationCode"
                className={styles.input}
              />
            </div>
            <div>
              <input
                type="hidden"
                name="username"
                value={name}
                className={styles.input}
              />
            </div>
            <button className={styles.loginBtn} onClick={() => confirm()}>
              Confirm account
            </button>
          </form>
          <div className={styles.registerOrSignin}>
            Didnt recieve a code?
            <form id="myForm2">
              <div>
                <input
                  type="hidden"
                  name="username"
                  value={name}
                  className={styles.input}
                />
              </div>
              <button
                className={styles.registerOrSignin2}
                onClick={() => resend()}>
                {' '}
                Send a new code
              </button>
            </form>
          </div>
        </div>
      </main>
    </div>
  );
}
